In [22]:
import Quandl
from Quandl.Quandl import DatasetNotFound    
AUTH_TOKEN = "goyzFZSAkjSMWhbBFSF_"
%matplotlib inline 
import matplotlib.pylab
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go
import pandas as pd

In [16]:
town_to_code_map = {
    "Sagaponack": "C09421", 
    "Greenport": "C06109", 
    "Amagansett": "ZAMAGANSETT",
    "Bridgehampton":"C16039",
    "Westhampton Beach": "N06650",
    "Sag Harbor": "C09970",
    "East Hampton": "N02372",
    "South Hampton": "C09538",
    "Water Mill": "C08225"    
}

metric_to_code_map = {
    "Sold For Loss": "SFL",
    "Sold For Gain": "SFG",
    "Top Tier": "TT",
    "Rentals": "RMP",
    "Median Value Per Square Foot": "MVSF",
    "Monthly Index": "A",
    "Listings With Price Cuts": "LPC",
    "Median Sale Price": "MSP",
    "Median Sale Price Per Square Foot": "MSPSF"
}

In [54]:
import collections
town_data = collections.defaultdict(lambda : collections.defaultdict(dict))
for town, town_code in town_code_map.iteritems():
    for metric, metric_code in metric_to_code_map.iteritems():
        try:
            df = Quandl.get("ZILL/"+ town_code + "_" + metric_code, authtoken=AUTH_TOKEN)
        except DatasetNotFound:
            print "ZILL/"+ town_code + "_" + metric_code + " failed"
            next
        print "ZILL/"+ town_code + "_" + metric_code + " succeeded"
        df.index = df.index.format()
        town_data[town][metric] = df.to_dict()['Value']

ZILL/C16039_LPC succeeded
ZILL/C16039_A succeeded
ZILL/C16039_MSPSF failed
ZILL/C16039_MSPSF succeeded
ZILL/C16039_SFG failed
ZILL/C16039_SFG succeeded
ZILL/C16039_MSP failed
ZILL/C16039_MSP succeeded
ZILL/C16039_RMP succeeded
ZILL/C16039_MVSF succeeded
ZILL/C16039_SFL failed
ZILL/C16039_SFL succeeded
ZILL/C16039_TT failed
ZILL/C16039_TT succeeded
ZILL/N02372_LPC succeeded
ZILL/N02372_A succeeded
ZILL/N02372_MSPSF failed
ZILL/N02372_MSPSF succeeded
ZILL/N02372_SFG succeeded
ZILL/N02372_MSP succeeded
ZILL/N02372_RMP succeeded
ZILL/N02372_MVSF succeeded
ZILL/N02372_SFL succeeded
ZILL/N02372_TT succeeded
ZILL/C08225_LPC succeeded
ZILL/C08225_A succeeded
ZILL/C08225_MSPSF succeeded
ZILL/C08225_SFG succeeded
ZILL/C08225_MSP succeeded
ZILL/C08225_RMP succeeded
ZILL/C08225_MVSF succeeded
ZILL/C08225_SFL succeeded
ZILL/C08225_TT succeeded
ZILL/C09970_LPC succeeded
ZILL/C09970_A failed
ZILL/C09970_A succeeded
ZILL/C09970_MSPSF failed
ZILL/C09970_MSPSF succeeded
ZILL/C09970_SFG succeeded
ZILL/C09970_MSP succeeded
ZILL/C09970_RMP succeeded
ZILL/C09970_MVSF failed
ZILL/C09970_MVSF succeeded
ZILL/C09970_SFL succeeded
ZILL/C09970_TT failed
ZILL/C09970_TT succeeded
ZILL/N06650_LPC succeeded
ZILL/N06650_A failed
ZILL/N06650_A succeeded
ZILL/N06650_MSPSF failed
ZILL/N06650_MSPSF succeeded
ZILL/N06650_SFG failed
ZILL/N06650_SFG succeeded
ZILL/N06650_MSP failed
ZILL/N06650_MSP succeeded
ZILL/N06650_RMP succeeded
ZILL/N06650_MVSF failed
ZILL/N06650_MVSF succeeded
ZILL/N06650_SFL failed
ZILL/N06650_SFL succeeded
ZILL/N06650_TT failed
ZILL/N06650_TT succeeded
ZILL/C09538_LPC succeeded
ZILL/C09538_A succeeded
ZILL/C09538_MSPSF failed
ZILL/C09538_MSPSF succeeded
ZILL/C09538_SFG succeeded
ZILL/C09538_MSP failed
ZILL/C09538_MSP succeeded
ZILL/C09538_RMP succeeded
ZILL/C09538_MVSF succeeded
ZILL/C09538_SFL failed
ZILL/C09538_SFL succeeded
ZILL/C09538_TT succeeded
ZILL/C09421_LPC succeeded
ZILL/C09421_A succeeded
ZILL/C09421_MSPSF failed
ZILL/C09421_MSPSF succeeded
ZILL/C09421_SFG failed
ZILL/C09421_SFG succeeded
ZILL/C09421_MSP failed
ZILL/C09421_MSP succeeded
ZILL/C09421_RMP succeeded
ZILL/C09421_MVSF succeeded
ZILL/C09421_SFL failed
ZILL/C09421_SFL succeeded
ZILL/C09421_TT succeeded
ZILL/C06109_LPC succeeded
ZILL/C06109_A succeeded
ZILL/C06109_MSPSF failed
ZILL/C06109_MSPSF succeeded
ZILL/C06109_SFG succeeded
ZILL/C06109_MSP succeeded
ZILL/C06109_RMP succeeded
ZILL/C06109_MVSF succeeded
ZILL/C06109_SFL succeeded
ZILL/C06109_TT succeeded
ZILL/ZAMAGANSETT_LPC failed
ZILL/ZAMAGANSETT_LPC succeeded
ZILL/ZAMAGANSETT_A failed
ZILL/ZAMAGANSETT_A succeeded
ZILL/ZAMAGANSETT_MSPSF failed
ZILL/ZAMAGANSETT_MSPSF succeeded
ZILL/ZAMAGANSETT_SFG failed
ZILL/ZAMAGANSETT_SFG succeeded
ZILL/ZAMAGANSETT_MSP failed
ZILL/ZAMAGANSETT_MSP succeeded
ZILL/ZAMAGANSETT_RMP failed
ZILL/ZAMAGANSETT_RMP succeeded
ZILL/ZAMAGANSETT_MVSF failed
ZILL/ZAMAGANSETT_MVSF succeeded
ZILL/ZAMAGANSETT_SFL failed
ZILL/ZAMAGANSETT_SFL succeeded
ZILL/ZAMAGANSETT_TT failed
ZILL/ZAMAGANSETT_TT succeeded

In [55]:
import json
with open('house_data.json', 'w') as outfile:
    json.dump(town_data, outfile)

In [77]:
metric_df = pd.concat([town_data[town]["Rentals"] for town in town_data.keys()], axis=1)
metric_df.columns = town_data.keys()
metric_df

,East Hampton,South Hampton,Sagaponack,Amagansett,Bridgehampton,Water Mill,Sag Harbor,Westhampton Beach,Greenport
1996-04-30,NaN,NaN,NaN,190700,NaN,NaN,NaN,NaN,NaN
1996-05-31,NaN,NaN,NaN,181800,NaN,NaN,NaN,NaN,NaN
1996-06-30,NaN,NaN,NaN,176800,NaN,NaN,NaN,NaN,NaN
1996-07-31,NaN,NaN,NaN,173100,NaN,NaN,NaN,NaN,NaN
1996-08-31,NaN,NaN,NaN,168200,NaN,NaN,NaN,NaN,NaN
1996-09-30,NaN,NaN,NaN,163200,NaN,NaN,NaN,NaN,NaN
1996-10-31,NaN,NaN,NaN,160300,NaN,NaN,NaN,NaN,NaN
1996-11-30,NaN,NaN,NaN,159500,NaN,NaN,NaN,NaN,NaN
1996-12-31,NaN,NaN,NaN,159300,NaN,NaN,NaN,NaN,NaN
1997-01-31,NaN,NaN,NaN,220800,NaN,NaN,NaN,NaN,NaN
1997-02-28,NaN,NaN,NaN,216500,NaN,NaN,NaN,NaN,NaN
1997-03-31,NaN,NaN,NaN,214900,NaN,NaN,NaN,NaN,NaN
1997-04-30,NaN,NaN,NaN,217700,NaN,NaN,NaN,NaN,NaN
1997-05-31,NaN,NaN,NaN,218800,NaN,NaN,NaN,NaN,NaN
1997-06-30,NaN,NaN,NaN,214800,NaN,NaN,NaN,NaN,NaN
1997-07-31,NaN,NaN,NaN,209100,NaN,NaN,NaN,NaN,NaN
1997-08-31,NaN,NaN,NaN,204900,NaN,NaN,NaN,NaN,NaN
1997-09-30,NaN,NaN,NaN,202800,NaN,NaN,NaN,NaN,NaN
1997-10-31,NaN,NaN,NaN,203600,NaN,NaN,NaN,NaN,NaN
1997-11-30,NaN,NaN,NaN,204600,NaN,NaN,NaN,NaN,NaN
1997-12-31,NaN,NaN,NaN,205200,NaN,NaN,NaN,NaN,NaN
1998-01-31,NaN,NaN,NaN,207200,NaN,NaN,NaN,NaN,NaN
1998-02-28,NaN,NaN,NaN,210000,NaN,NaN,NaN,NaN,NaN
1998-03-31,NaN,NaN,NaN,211200,NaN,NaN,NaN,NaN,NaN
1998-04-30,NaN,NaN,NaN,210700,NaN,NaN,NaN,NaN,NaN
1998-05-31,NaN,NaN,NaN,211900,NaN,NaN,NaN,NaN,NaN
1998-06-30,NaN,NaN,NaN,214700,NaN,NaN,NaN,NaN,NaN
1998-07-31,NaN,NaN,NaN,216900,NaN,NaN,NaN,NaN,NaN
1998-08-31,NaN,NaN,NaN,216700,NaN,NaN,NaN,NaN,NaN
1998-09-30,NaN,NaN,NaN,215100,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2013-08-31,30000,35000,60000,577500,40000,45000,25000,35000,7000
2013-09-30,30000,1400,65000,576400,40000,50000,25000,32500,5500
2013-10-31,36000,40000,65000,577500,46000,60000,30000,45000,5500
2013-11-30,37000,45000,60000,579800,46000,65000,30000,65000,5500
2013-12-31,38000,45000,65000,580000,48000,68000,30000,45000,5500
2014-01-31,38000,45000,65000,579100,45000,68000,35000,53900,5500
2014-02-28,37000,45000,65000,582900,45000,68000,35000,53900,7000
2014-03-31,35000,45000,65000,583500,45000,60000,35000,50000,7500
2014-04-30,35000,42000,65000,571800,45000,59600,35000,45000,7500
2014-05-31,35000,40000,65000,552200,45000,55000,30000,40000,7000
2014-06-30,32000,40000,60000,539200,35000,50000,29500,40000,5500
2014-07-31,25000,35000,55000,540100,35000,45000,27000,40000,5500
2014-08-31,30000,35000,55000,549700,35000,45000,25000,40000,5000
2014-09-30,35000,35000,50000,554400,35000,48000,25000,40000,5000
2014-10-31,40000,42000,50000,557800,40000,55000,30000,70000,5500
2014-11-30,35000,50000,60000,561000,55000,65000,35000,53900,7000
2014-12-31,47000,49000,65000,558700,55000,65000,35000,60000,6500
2015-01-31,39500,NaN,65000,553800,50000,60000,34000,45000,9000
2015-02-28,35000,NaN,60000,538400,50000,60000,34000,45000,10000
2015-03-31,38000,NaN,65000,543000,50000,65000,35000,53000,8000
2015-04-30,35000,NaN,60000,545400,50000,60000,32500,45000,10000
2015-05-31,30000,NaN,55000,543800,34740,55000,22000,40000,9000
2015-06-30,30000,NaN,55000,544900,45000,59000,30000,32000,10000
2015-07-31,NaN,NaN,NaN,555000,NaN,NaN,NaN,NaN,NaN
2015-08-31,NaN,NaN,NaN,551400,NaN,NaN,NaN,NaN,NaN
2015-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-31,35000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-31,39000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
metric_dfs = []

for metric in metric_to_code_map.keys():
    metric_df
    for town in town_to_code_map.keys():
        metric_df[]
    metric_dfs[metric] = metric_df

            Listings With Price Cuts  Median Sale Price  \
2010-02-28                    8.0000                NaN
2010-03-31                    9.3750                NaN
2010-04-30                   12.1212                NaN
2010-05-31                   11.4286                NaN
2010-06-30                   14.2857                NaN
2010-07-31                    5.2632                NaN
2010-08-31                   10.8108                NaN
2010-09-30                   15.3846                NaN
2010-10-31                   17.9487                NaN
2010-11-30                   13.1579                NaN
2010-12-31                    8.3333                NaN
2011-01-31                    9.3750                NaN
2011-02-28                   13.1579                NaN
2011-03-31                   13.1579                NaN
2011-04-30                   12.1951                NaN
2011-05-31                   15.5556                NaN
2011-06-30                    9.8039                NaN
2011-07-31                    8.1967                NaN
2011-08-31                    9.3333                NaN
2011-09-30                   10.4651                NaN
2011-10-31                   10.2041                NaN
2011-11-30                   10.0000                NaN
2011-12-31                   11.1111                NaN
2012-01-31                   11.0236                NaN
2012-02-29                   10.8108                NaN
2012-03-31                    8.3333                NaN
2012-04-30                   10.5590                NaN
2012-05-31                   11.3095                NaN
2012-06-30                    8.9172                NaN
2012-07-31                    7.5472                NaN
...                              ...                ...
2013-06-30                    2.1053                NaN
2013-07-31                    5.4348                NaN
2013-08-31                   10.8696                NaN
2013-09-30                   10.6383                NaN
2013-10-31                   14.9425                NaN
2013-11-30                   14.2857                NaN
2013-12-31                    5.8140                NaN
2014-01-31                    8.6957                NaN
2014-02-28                    8.0460                NaN
2014-03-31                    7.0000                NaN
2014-04-30                   11.0000                NaN
2014-05-31                    6.5217                NaN
2014-06-30                    8.8000                NaN
2014-07-31                    5.3435                NaN
2014-08-31                    3.8168                NaN
2014-09-30                    5.6338                NaN
2014-10-31                    4.6053                NaN
2014-11-30                    4.5752                NaN
2014-12-31                    7.0064                NaN
2015-01-31                       NaN                NaN
2015-02-28                    2.1739                NaN
2015-03-31                       NaN                NaN
2015-04-30                       NaN                NaN
2015-05-31                       NaN                NaN
2015-06-30                       NaN                NaN
2015-09-30                       NaN            1723100
2015-10-31                       NaN            1718500
2015-11-30                       NaN            1708800
2015-12-31                       NaN            1730300
2016-01-31                       NaN            1711600

            Median Sale Price Per Square Foot  Median Value Per Square Foot  \
2010-02-28                                NaN                           NaN
2010-03-31                                NaN                           NaN
2010-04-30                                NaN                           NaN
2010-05-31                                NaN                           NaN
2010-06-30                                NaN                           NaN
2010-07-31                                NaN                           NaN
2010-08-31                                NaN                           NaN
2010-09-30                                NaN                           NaN
2010-10-31                                NaN                           NaN
2010-11-30                                NaN                           NaN
2010-12-31                                NaN                           NaN
2011-01-31                                NaN                           NaN
2011-02-28                                NaN                           NaN
2011-03-31                                NaN                           NaN
2011-04-30                                NaN                           NaN
2011-05-31                                NaN                           NaN
2011-06-30                                NaN                           NaN
2011-07-31                                NaN                           NaN
2011-08-31                                NaN                           NaN
2011-09-30                                NaN                           NaN
2011-10-31                                NaN                           NaN
2011-11-30                                NaN                           NaN
2011-12-31                                NaN                           NaN
2012-01-31                                NaN                           NaN
2012-02-29                                NaN                           NaN
2012-03-31                                NaN                           NaN
2012-04-30                                NaN                           NaN
2012-05-31                                NaN                           NaN
2012-06-30                                NaN                           NaN
2012-07-31                                NaN                           NaN
...                                       ...                           ...
2013-06-30                                NaN                           NaN
2013-07-31                                NaN                           NaN
2013-08-31                                NaN                           NaN
2013-09-30                                NaN                           NaN
2013-10-31                                NaN                           NaN
2013-11-30                                NaN                           NaN
2013-12-31                                NaN                           NaN
2014-01-31                                NaN                           NaN
2014-02-28                                NaN                           NaN
2014-03-31                                NaN                           NaN
2014-04-30                                NaN                           NaN
2014-05-31                                NaN                           NaN
2014-06-30                                NaN                           NaN
2014-07-31                                NaN                           NaN
2014-08-31                                NaN                           NaN
2014-09-30                                NaN                           NaN
2014-10-31                                NaN                           NaN
2014-11-30                                NaN                           NaN
2014-12-31                                NaN                           NaN
2015-01-31                                NaN                           NaN
2015-02-28                                NaN                           NaN
2015-03-31                                NaN                           NaN
2015-04-30                                NaN                           NaN
2015-05-31                                NaN                           NaN
2015-06-30                                NaN                           NaN
2015-09-30                            1723100                           852
2015-10-31                            1718500                           833
2015-11-30                            1708800                           818
2015-12-31                            1730300                           816
2016-01-31                            1711600                           803

            Monthly Index  Rentals  Sold For Gain  Sold For Loss  Top Tier
2010-02-28            NaN      NaN            NaN            NaN       NaN
2010-03-31            NaN      NaN            NaN            NaN       NaN
2010-04-30            NaN      NaN            NaN            NaN       NaN
2010-05-31            NaN      NaN            NaN            NaN       NaN
2010-06-30            NaN      NaN            NaN            NaN       NaN
2010-07-31            NaN      NaN            NaN            NaN       NaN
2010-08-31            NaN      NaN            NaN            NaN       NaN
2010-09-30            NaN      NaN            NaN            NaN       NaN
2010-10-31            NaN      NaN            NaN            NaN       NaN
2010-11-30            NaN      NaN            NaN            NaN       NaN
2010-12-31            NaN      NaN            NaN            NaN       NaN
2011-01-31            NaN      NaN            NaN            NaN       NaN
2011-02-28            NaN      NaN            NaN            NaN       NaN
2011-03-31            NaN      NaN            NaN            NaN       NaN
2011-04-30            NaN      NaN            NaN            NaN       NaN
2011-05-31            NaN      NaN            NaN            NaN       NaN
2011-06-30            NaN      NaN            NaN            NaN       NaN
2011-07-31            NaN      NaN            NaN            NaN       NaN
2011-08-31            NaN    25000            NaN            NaN       NaN
2011-09-30            NaN      NaN            NaN            NaN       NaN
2011-10-31            NaN    34800            NaN            NaN       NaN
2011-11-30            NaN    59000            NaN            NaN       NaN
2011-12-31            NaN    60000            NaN            NaN       NaN
2012-01-31            NaN    59000            NaN            NaN       NaN
2012-02-29            NaN    60000            NaN            NaN       NaN
2012-03-31            NaN    60000            NaN            NaN       NaN
2012-04-30            NaN    60000            NaN            NaN       NaN
2012-05-31            NaN    50000            NaN            NaN       NaN
2012-06-30            NaN    49000            NaN            NaN       NaN
2012-07-31            NaN    49000            NaN            NaN       NaN
...                   ...      ...            ...            ...       ...
2013-06-30            NaN    40000            NaN            NaN       NaN
2013-07-31            NaN    45000            NaN            NaN       NaN
2013-08-31            NaN    40000            NaN            NaN       NaN
2013-09-30            NaN    40000            NaN            NaN       NaN
2013-10-31            NaN    46000            NaN            NaN       NaN
2013-11-30            NaN    46000            NaN            NaN       NaN
2013-12-31            NaN    48000            NaN            NaN       NaN
2014-01-31            NaN    45000            NaN            NaN       NaN
2014-02-28            NaN    45000            NaN            NaN       NaN
2014-03-31            NaN    45000            NaN            NaN       NaN
2014-04-30            NaN    45000            NaN            NaN       NaN
2014-05-31            NaN    45000            NaN            NaN       NaN
2014-06-30            NaN    35000            NaN            NaN       NaN
2014-07-31            NaN    35000            NaN            NaN       NaN
2014-08-31            NaN    35000            NaN            NaN       NaN
2014-09-30            NaN    35000            NaN            NaN       NaN
2014-10-31            NaN    40000            NaN            NaN       NaN
2014-11-30            NaN    55000            NaN            NaN       NaN
2014-12-31            NaN    55000            NaN            NaN       NaN
2015-01-31            NaN    50000            NaN            NaN       NaN
2015-02-28            NaN    50000            NaN            NaN       NaN
2015-03-31            NaN    50000            NaN            NaN       NaN
2015-04-30            NaN    50000            NaN            NaN       NaN
2015-05-31            NaN    34740            NaN            NaN       NaN
2015-06-30            NaN    45000            NaN            NaN       NaN
2015-09-30        1723100      NaN        1723100            852       852
2015-10-31        1718500      NaN        1718500            833       833
2015-11-30        1708800      NaN        1708800            818       818
2015-12-31        1730300      NaN        1730300            816       816
2016-01-31        1711600      NaN        1711600            803       803

[70 rows x 9 columns]
            Listings With Price Cuts  Median Sale Price  \
1997-01-31                       NaN                NaN
1997-02-28                       NaN                NaN
1997-03-31                       NaN                NaN
1997-04-30                       NaN                NaN
1997-05-31                       NaN                NaN
1997-06-30                       NaN                NaN
1997-07-31                       NaN                NaN
1997-08-31                       NaN                NaN
1997-09-30                       NaN                NaN
1997-10-31                       NaN                NaN
1997-11-30                       NaN                NaN
1997-12-31                       NaN                NaN
1998-01-31                       NaN                NaN
1998-02-28                       NaN                NaN
1998-03-31                       NaN                NaN
1998-04-30                       NaN                NaN
1998-05-31                       NaN                NaN
1998-06-30                       NaN                NaN
1998-07-31                       NaN                NaN
1998-08-31                       NaN                NaN
1998-09-30                       NaN                NaN
1998-10-31                       NaN                NaN
1998-11-30                       NaN                NaN
1998-12-31                       NaN                NaN
1999-01-31                       NaN                NaN
1999-02-28                       NaN                NaN
1999-03-31                       NaN                NaN
1999-04-30                       NaN                NaN
1999-05-31                       NaN                NaN
1999-06-30                       NaN                NaN
...                              ...                ...
2013-08-31                    8.0717                NaN
2013-09-30                   10.0000                NaN
2013-10-31                    9.8131                NaN
2013-11-30                   10.6796                NaN
2013-12-31                    7.8125            1162500
2014-01-31                    5.2356                NaN
2014-02-28                    4.4944                NaN
2014-03-31                    8.1761                NaN
2014-04-30                    9.8160                NaN
2014-05-31                    7.4534                NaN
2014-06-30                    9.6045                NaN
2014-07-31                   13.0682                NaN
2014-08-31                   12.9944                NaN
2014-09-30                   13.8298                NaN
2014-10-31                    8.2927                NaN
2014-11-30                    9.8039                NaN
2014-12-31                    8.7379                NaN
2015-01-31                       NaN                NaN
2015-02-28                    2.1053                NaN
2015-03-31                       NaN                NaN
2015-04-30                       NaN                NaN
2015-05-31                       NaN                NaN
2015-06-30                       NaN                NaN
2015-07-31                       NaN                NaN
2015-08-31                       NaN                NaN
2015-09-30                       NaN                NaN
2015-10-31                       NaN                NaN
2015-11-30                       NaN                NaN
2015-12-31                       NaN                NaN
2016-01-31                       NaN                NaN

            Median Sale Price Per Square Foot  Median Value Per Square Foot  \
1997-01-31                                NaN                           156
1997-02-28                                NaN                           156
1997-03-31                                NaN                           158
1997-04-30                                NaN                           161
1997-05-31                                NaN                           161
1997-06-30                                NaN                           159
1997-07-31                                NaN                           159
1997-08-31                                NaN                           161
1997-09-30                                NaN                           160
1997-10-31                                NaN                           160
1997-11-30                                NaN                           160
1997-12-31                                NaN                           161
1998-01-31                                NaN                           161
1998-02-28                                NaN                           162
1998-03-31                                NaN                           164
1998-04-30                                NaN                           168
1998-05-31                                NaN                           173
1998-06-30                                NaN                           178
1998-07-31                                NaN                           181
1998-08-31                                NaN                           182
1998-09-30                                NaN                           183
1998-10-31                                NaN                           185
1998-11-30                                NaN                           188
1998-12-31                                NaN                           187
1999-01-31                                NaN                           185
1999-02-28                                NaN                           186
1999-03-31                                NaN                           187
1999-04-30                                NaN                           188
1999-05-31                                NaN                           189
1999-06-30                                NaN                           192
...                                       ...                           ...
2013-08-31                             974900                           471
2013-09-30                             988000                           477
2013-10-31                            1012400                           482
2013-11-30                            1040500                           487
2013-12-31                            1058200                           497
2014-01-31                            1067400                           506
2014-02-28                            1065600                           508
2014-03-31                            1087500                           515
2014-04-30                            1139200                           535
2014-05-31                            1196600                           562
2014-06-30                            1235500                           579
2014-07-31                            1260800                           584
2014-08-31                            1273600                           587
2014-09-30                            1287600                           597
2014-10-31                            1303300                           607
2014-11-30                            1316800                           613

In [61]:
trace = go.Scatter( x=sagaponack_median_per_sq_ft.index, y=sagaponack_median_per_sq_ft['Value'] )
data = [trace]

py.iplot(data)